#!/bin/bash

# https://unix.stackexchange.com/questions/230047/how-to-list-all-targets-in-make
make -qp | 
    awk -F':' '/^[a-zA-Z0-9][^$#\/\t=]*:([^=]|$)/ {split($1,A,/ /);for(i in A)print A[i]}' |
    sort -u

